Add support for nextjs ssr on ui express server, move package page to react
aspen-cloud/browser-functions pull request #4
Opened 2020-12-10 22:00 UTC by wernst

2020-12-10 22:10 UTC, wernst commented
Going to fix conflicts, didnt rebase before pushing

2020-12-10 23:44 UTC, matlin commented on server/ui.js
> +        if(!dependencies) {
`400` (i.e. "Bad Request") might be better

2020-12-10 23:45 UTC, matlin requested changes
This is amazing dude. Going to be 100X easier to build the frontend

2020-12-11 00:07 UTC, matlin commented
I'm gonna merge but we can fix status codes in another commit.

2020-12-11 00:08 UTC, merged